PHP_1-4/yii-world/models/Country.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "country".
 *
 * @property int $country_id
 * @property string $code Two-letter country code (ISO 3166-1 alpha-2)
 * @property string $name English country name
 * @property string $official_name Official English country name
 * @property string $iso3 Three-letter country code (ISO 3166-1 alpha-3)
 * @property int $number Three-digit country number (ISO 3166-1 numeric)
 * @property string $currency
 * @property string $capital
 * @property int $area
 * @property int $continent_id
 * @property string $coords
 * @property int $display_order
 *
 * @property Continent $continent
 * @property Region[] $regions
 */
class Country extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'country';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['code', 'name', 'official_name', 'iso3', 'number', 'currency', 'capital', 'area', 'continent_id', 'coords'], 'required'],
            [['number', 'area', 'continent_id', 'display_order'], 'integer'],
            [['code'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 64],
            [['official_name', 'currency', 'capital'], 'string', 'max' => 128],
            [['iso3'], 'string', 'max' => 3],
            [['coords'], 'string', 'max' => 255],
            [['code'], 'unique'],
            [['continent_id'], 'exist', 'skipOnError' => true, 'targetClass' => Continent::className(), 'targetAttribute' => ['continent_id' => 'continent_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'country_id' => 'Country ID',
            'code' => 'Code',
            'name' => 'Name',
            'official_name' => 'Official Name',
            'iso3' => 'Iso3',
            'number' => 'Number',
            'currency' => 'Currency',
            'capital' => 'Capital',
            'area' => 'Area',
            'continent_id' => 'Continent',
            'coords' => 'Coords',
            'display_order' => 'Display Order',
        ];
    }

    /**
     * Gets query for [[Continent]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getContinent()
    {
        return $this->hasOne(Continent::className(), ['continent_id' => 'continent_id']);
    }

    /**
     * Gets query for [[Regions]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRegions()
    {
        return $this->hasMany(Region::className(), ['country_id' => 'country_id']);
    }
}

PHP_1-4/yii-world/controllers/ContinentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ContinentSearch;
use app\models\Continent;
use app\models\Country;
use app\models\Region;
use app\models\City;
use app\models\WorldForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * ContinentController implements the CRUD actions for Continent model.
 */
class ContinentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Continent models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ContinentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionWorldForm()
    {
        $model = new WorldForm();
        $continents = Continent::find()->asArray()->all();
        $continent = null;
        $countries = null;
        $regions = null;
        $cities = null;

        if (Yii::$app->request->isPjax) {
            $model->load(Yii::$app->request->post());
            $continent = Continent::find()->where(['continent_id' => $model->continent_id])->asArray()->one();
            if ($model->continent_id > 0) {
                $countries = Country::find()->where(['continent_id' => $model->continent_id])->asArray()->all();
                
            }
            if($model->country_id > 0){
                    
                $regions = Region::find()
                ->select('region.*, region_language.name_language as name_language')
                ->leftJoin('region_language', '`region_language`.`region_id` = `region`.`region_id`')
                ->where(['region_language.language' => 'en', 'region.country_id' => $model->country_id])
                ->asArray()
                ->all();

            }
            if($model->region_id > 0){

                $cities = City::find()
                ->select('city.*, city_language.name_language as name_language')
                ->leftJoin('city_language', '`city_language`.`city_id` = `city`.`city_id`')
                ->where(['city_language.language' => 'en', 'city.region_id' => $model->region_id])
                ->asArray()
                ->all();
            }
        }

        return $this->render('world-form', [
            'model' => $model,
            'continents' => $continents,
            'continent' => $continent,
            'countries' => $countries,
            'regions' => $regions,
            'cities' => $cities
        ]);
    }

    public function actionList()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('list', ['continents' => $continents]);
    }

    /**
     * Displays a single Continent model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($code = 'AF')
    {
        $continent = Continent::find()->where(['code' => $code])->one();

        $countriesProvider = new ActiveDataProvider([
            'query' => Country::find()->where(['continent_id' => $continent->continent_id]),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('view', [
            'continent' => $continent,
            'countriesProvider' => $countriesProvider,
            //'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Continent model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Continent();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->continent_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Continent model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->continent_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Continent model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Continent model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Continent the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Continent::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

PHP_1-4/yii-world/controllers/CountryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Country;
use app\models\CountrySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CountryController implements the CRUD actions for Country model.
 */
class CountryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Country models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CountrySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Country model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($code = "UA")
    {
        $country = Country::find()->where(['code' => $code])->one();

        return $this->render('view', [
            'country' => $country,
            //'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Country model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Country();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Country model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->country_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Country model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Country model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Country the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Country::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

PHP_1-4/yii-world/views/country/_form.php
<?php

use app\models\Continent;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Country */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'official_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'iso3')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'number')->textInput() ?>

    <?= $form->field($model, 'currency')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'capital')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'area')->textInput() ?>

    <!--<?= $form->field($model, 'continent_id')->textInput() ?> -->

    <?= $form->field($model, 'continent_id')->dropDownList(ArrayHelper::map(Continent::find()->all(), 'continent_id', 'name')); ?>

    <?= $form->field($model, 'coords')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'display_order')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

PHP_1-4/yii-world/views/country/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CountrySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="country-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'country_id') ?>

    <?= $form->field($model, 'code') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'official_name') ?>

    <?= $form->field($model, 'iso3') ?>

    <?php // echo $form->field($model, 'number') ?>

    <?php // echo $form->field($model, 'currency') ?>

    <?php // echo $form->field($model, 'capital') ?>

    <?php // echo $form->field($model, 'area') ?>

    <?php // echo $form->field($model, 'continent_id') ?>

    <?php // echo $form->field($model, 'coords') ?>

    <?php // echo $form->field($model, 'display_order') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

PHP_1-4/yii-world/views/country/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Country */

$this->title = 'Create Country';
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

PHP_1-4/yii-world/views/country/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\CountrySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Countries';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="country-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Country', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'country_id',
            'code',
            'name',
            'official_name',
            'iso3',
            //'number',
            //'currency',
            //'capital',
            //'area',
            //'continent_id',
            //'coords',
            //'display_order',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

PHP_1-4/yii-world/views/country/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Country */

$this->title = 'Update Country: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Countries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->country_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="country-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

PHP_1-4/yii-world/views/country/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Country */

$this->title = $country->name;
$this->params['breadcrumbs'][] = ['label' => $country->continent->name, 'url' => ['continent/view', 'code' => $country->continent->code]];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="container">
    <div class="row">
        <div class="col-sm-6"> <?//country-view ?>
        
            <h1><?= Html::encode($this->title) ?></h1>
        
            <p>
                <?= Html::a('Update', ['update', 'id' => $country->country_id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $country->country_id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => 'Are you sure you want to delete this item?',
                        'method' => 'post',
                    ],
                ]) ?>
            </p>
        
            <?= DetailView::widget([
                'model' => $country,
                'attributes' => [
                    'country_id',
                    'code',
                    'name',
                    'official_name',
                    'iso3',
                    'number',
                    'currency',
                    'capital',
                    'area',
                    [
                        'attribute' => 'Flag',
                        'value' => "@web/images/countries/png250px/" .strtolower($country->code). ".png",
                        'format' => ['image', ['width'=>'140', 'height'=>'100']],
                    ],
                    'continent_id',
                    'coords',
                    'display_order',
                ],
            ]) ?>
        </div>
        
        <div class="col-sm-6" id="map" style="height: 400px; margin-top: 113px">
            <?php 
        
                $first_str = strpos($country->coords, ",");
                $lat = substr($country->coords, 1, $first_str - 1);
                $lng = substr($country->coords, $first_str + 1, -1);
                
            ?>
            <script>
                // Initialize and add the map
                function initMap() {
                // The location of Uluru
                    const uluru = { lat: <?= $lat;?>, lng: <?= $lng;?> };
                // The map, centered at Uluru
                    const map = new google.maps.Map(document.getElementById("map"), {
                        zoom: 4,
                        center: uluru,
                    });
                // The marker, positioned at Uluru
                    const marker = new google.maps.Marker({
                        position: uluru,
                        map: map,
                    });
                }
            </script>
            <script
                    src="https://maps.googleapis.com/maps/api/js?&callback=initMap&libraries=&v=weekly$sensors=false"
                    defer
            ></script>
        </div>
    </div>
</div>